version: '3.8'

services:
  myocardial-blood-flow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: circle-assessment-mbf
    working_dir: /app
    volumes:
      - .:/app   # Mount source code for live development
      - ./input_data:/app/input_data   # Mount input data directory
      - ./results:/app/results   # Mount results directory to persist output files
      - ./logs:/app/logs   # Mount logs directory to persist log files
    environment:
      - PYTHONPATH=/app
      - MPLBACKEND=Agg  # Ensure matplotlib uses non-GUI backend
    restart: unless-stopped
    
